name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.0
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake
      run: cmake -GNinja -A x64 -S . -B build

    - name: Build
      run: cmake --build build --target at-example at-test --config ${{ matrix.mode }}

    - name: Run tests
      run: |
        cd build
        ${{ matrix.mode }}\at-test.exe
