name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [Debug, Release]

    env:
      CXX: cl
      CC: cl

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: Setup Build Tools
      run: |
        Install-module posh-vs -Force
        Install-PoshVs

    - name: CMake
      run: cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}

    - name: Build
      run: cmake --build build --target at-example at-test

    - name: Run tests
      run: |
        cd build
        .\at-test.exe
