name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [Debug, Release]

    env:
      CXX: cl.exe
      CC: cl.exe

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    
    - name: Setup Build Tools
      run: |
        function Invoke-Environment {
            param
            (
                # Any cmd shell command, normally a configuration batch file.
                [Parameter(Mandatory=$true)]
                [string] $Command
            )

            $Command = "`"" + $Command + "`""
            cmd /c "$Command > nul 2>&1 && set" | . { process {
                if ($_ -match '^([^=]+)=(.*)') {
                    [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])
                }
            }}
        }
        $VCVARS=$(& "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\vcvars64.bat)
        Invoke-Environment $VCVARS 

    - name: CMake
      run: cmake -GNinja -S . -B build

    - name: Build
      run: cmake --build build --target at-example at-test --config ${{ matrix.mode }}

    - name: Run tests
      run: |
        cd build
        ${{ matrix.mode }}\at-test.exe
